name: "Build"

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Test
        run: pytest --cov=testreport/coverage --html=testreport/index.html --cov-report html

      - name: Run Stoat Action
        uses: stoat-dev/stoat-action@v0
        if: always()
